#!/usr/bin/env python3
"""
Script 6: Generate all paper figures.

Reads computed values from doc/computed_values/ (generated by other scripts)
and produces publication-quality PDF figures in doc/figures/.

Figures:
  1. Search loop + configuration space diagram (schematic)
  2. Convergence curves (main result figure)
  3. Multi-agent dynamics (entropy + JSD)
  4. Backbone x encoder heatmap
  5. Backbone distribution shift + AP trajectory with bug-fix annotations

Outputs:
  - doc/figures/figure1_schematic.pdf
  - doc/figures/convergence.pdf  (generated by compute_convergence.py, enhanced here)
  - doc/figures/agent_dynamics.pdf (generated by compute_agent_dynamics.py, enhanced here)
  - doc/figures/heatmap.pdf
  - doc/figures/trajectory.pdf
"""

import json
import os
import sys
import glob
import numpy as np
from collections import defaultdict
from pathlib import Path
from datetime import datetime

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec

COMPUTED_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'computed_values'))
FIGURES_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'figures'))
RESULTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'results'))
os.makedirs(FIGURES_DIR, exist_ok=True)

# Publication-quality settings
plt.rcParams.update({
    'font.size': 10,
    'axes.titlesize': 10,
    'axes.labelsize': 10,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'legend.fontsize': 8,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'font.family': 'serif',
    'text.usetex': False,
})


def load_json(filename):
    path = os.path.join(COMPUTED_DIR, filename)
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    print(f"Warning: {path} not found", file=sys.stderr)
    return None


def figure1_schematic():
    """Generate Figure 1: Search loop schematic."""
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.axis('off')

    # Draw boxes
    boxes = {
        'LLM Agent': (1, 4, 2, 1.2),
        'Config Space C': (4.5, 4, 2.5, 1.2),
        'Experiment\nRunner': (4.5, 1.5, 2.5, 1.2),
        'Leaderboard': (1, 1.5, 2, 1.2),
    }

    colors = {
        'LLM Agent': '#E3F2FD',
        'Config Space C': '#FFF3E0',
        'Experiment\nRunner': '#E8F5E9',
        'Leaderboard': '#F3E5F5',
    }

    for label, (x, y, w, h) in boxes.items():
        rect = mpatches.FancyBboxPatch(
            (x, y), w, h,
            boxstyle=mpatches.BoxStyle.Round(pad=0.1),
            facecolor=colors[label], edgecolor='black', linewidth=1.2
        )
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, label,
                ha='center', va='center', fontsize=9, fontweight='bold')

    # Draw arrows
    arrow_props = dict(arrowstyle='->', color='#333333', lw=1.5,
                       connectionstyle='arc3,rad=0')

    # LLM -> Config Space
    ax.annotate('', xy=(4.5, 4.6), xytext=(3, 4.6), arrowprops=arrow_props)
    ax.text(3.75, 4.9, '$\\pi_{\\mathrm{LLM}}(c | H_t)$', ha='center', fontsize=8)

    # Config Space -> Runner
    ax.annotate('', xy=(5.75, 2.7), xytext=(5.75, 4), arrowprops=arrow_props)
    ax.text(6.5, 3.35, '$c_t \\in \\mathcal{C}$', ha='center', fontsize=8)

    # Runner -> Leaderboard
    ax.annotate('', xy=(3, 2.1), xytext=(4.5, 2.1), arrowprops=arrow_props)
    ax.text(3.75, 1.7, '$y_t = f(c_t)$', ha='center', fontsize=8)

    # Leaderboard -> LLM
    ax.annotate('', xy=(2, 4), xytext=(2, 2.7), arrowprops=arrow_props)
    ax.text(0.8, 3.35, '$H_t$', ha='center', fontsize=8)

    # Title
    ax.text(5, 5.7, 'LLM-Guided Combinatorial Experiment Search',
            ha='center', fontsize=11, fontweight='bold')

    # Config space detail
    ax.text(8.5, 3.5, '$|\\mathcal{C}| \\approx 108K$\nBackbone $\\times$ Encoder\n'
            '$\\times$ Loss $\\times$ HP',
            ha='center', va='center', fontsize=7, style='italic',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', alpha=0.7))

    fig_path = os.path.join(FIGURES_DIR, 'figure1_schematic.pdf')
    plt.savefig(fig_path, bbox_inches='tight')
    print(f"Saved: {fig_path}", file=sys.stderr)
    plt.close()


def figure4_heatmap():
    """Generate Figure 4: Backbone x encoder heatmap."""
    data = load_json('ablation.json')
    if data is None:
        print("Skipping heatmap: ablation.json not found", file=sys.stderr)
        return

    # We need per-combo stats — load from anova.json or recompute
    anova_data = load_json('anova.json')
    if anova_data is None or 'group_stats' not in anova_data:
        print("Skipping heatmap: anova.json not found", file=sys.stderr)
        return

    group_stats = anova_data['group_stats']

    backbones = ['VJepa2', 'DINOv3-B', 'DINOv3-L', 'DINOv2', 'SigLIP2']
    encoders = ['Zipformer', 'Retention', 'BiMamba', 'Hybrid R-M']

    # Build heatmap matrices
    best_ap_matrix = np.full((len(backbones), len(encoders)), np.nan)
    mean_ap_matrix = np.full((len(backbones), len(encoders)), np.nan)
    count_matrix = np.zeros((len(backbones), len(encoders)), dtype=int)

    for i, bb in enumerate(backbones):
        for j, enc in enumerate(encoders):
            combo = f'{bb}+{enc}'
            if combo in group_stats:
                stats = group_stats[combo]
                best_ap_matrix[i, j] = stats['best']
                mean_ap_matrix[i, j] = stats['mean']
                count_matrix[i, j] = stats['count']

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4))

    # Best AP heatmap
    im1 = ax1.imshow(best_ap_matrix, cmap='YlOrRd', aspect='auto',
                      vmin=0.0, vmax=1.0)
    ax1.set_xticks(range(len(encoders)))
    ax1.set_xticklabels(encoders, rotation=30, ha='right')
    ax1.set_yticks(range(len(backbones)))
    ax1.set_yticklabels(backbones)
    ax1.set_title('(a) Best AP per backbone-encoder combination')
    plt.colorbar(im1, ax=ax1, shrink=0.8)

    # Annotate with values
    for i in range(len(backbones)):
        for j in range(len(encoders)):
            val = best_ap_matrix[i, j]
            cnt = count_matrix[i, j]
            if not np.isnan(val):
                color = 'white' if val > 0.7 else 'black'
                ax1.text(j, i, f'{val:.3f}\n(n={cnt})',
                         ha='center', va='center', fontsize=7, color=color)

    # Mean AP heatmap
    im2 = ax2.imshow(mean_ap_matrix, cmap='YlOrRd', aspect='auto',
                      vmin=0.0, vmax=1.0)
    ax2.set_xticks(range(len(encoders)))
    ax2.set_xticklabels(encoders, rotation=30, ha='right')
    ax2.set_yticks(range(len(backbones)))
    ax2.set_yticklabels(backbones)
    ax2.set_title('(b) Mean AP per backbone-encoder combination')
    plt.colorbar(im2, ax=ax2, shrink=0.8)

    for i in range(len(backbones)):
        for j in range(len(encoders)):
            val = mean_ap_matrix[i, j]
            cnt = count_matrix[i, j]
            if not np.isnan(val):
                color = 'white' if val > 0.5 else 'black'
                ax2.text(j, i, f'{val:.3f}\n(n={cnt})',
                         ha='center', va='center', fontsize=7, color=color)

    plt.tight_layout()
    fig_path = os.path.join(FIGURES_DIR, 'heatmap.pdf')
    plt.savefig(fig_path, bbox_inches='tight')
    print(f"Saved: {fig_path}", file=sys.stderr)
    plt.close()


def figure5_trajectory():
    """
    Generate Figure 5: AP trajectory over time with bug-fix annotations
    and backbone distribution shift.
    """
    import yaml

    # Load all experiments with timestamps and AP
    experiments = []
    idea_dirs = glob.glob(os.path.join(RESULTS_DIR, 'idea-*'))

    for idea_dir in idea_dirs:
        eval_path = os.path.join(idea_dir, 'ken_test_report.json')
        if not os.path.exists(eval_path):
            continue

        try:
            with open(eval_path) as f:
                eval_data = json.load(f)
            ap = eval_data.get('metrics', {}).get('average_precision')
            timestamp = eval_data.get('timestamp')
            if ap is None or timestamp is None:
                continue
            if not isinstance(ap, (int, float)) or np.isnan(ap):
                continue
        except Exception:
            continue

        # Get backbone
        config_path = os.path.join(idea_dir, 'resolved_config.yaml')
        backbone = 'Unknown'
        if os.path.exists(config_path):
            try:
                with open(config_path) as f:
                    cfg = yaml.safe_load(f)
                bb = cfg.get('backbone', {})
                name = bb.get('name', '').lower()
                if 'vjepa' in name:
                    backbone = 'VJepa2'
                elif 'dinov3' in name:
                    backbone = 'DINOv3'
                elif 'dinov2' in name:
                    backbone = 'DINOv2'
                elif 'siglip' in name:
                    backbone = 'SigLIP2'
                else:
                    backbone = 'Other'
            except Exception:
                pass

        experiments.append({
            'ap': float(ap),
            'timestamp': timestamp,
            'backbone': backbone,
        })

    if not experiments:
        print("No experiments with timestamps for trajectory", file=sys.stderr)
        return

    # Sort by timestamp
    experiments.sort(key=lambda x: x['timestamp'])

    # Parse dates
    dates = []
    for e in experiments:
        try:
            dt = datetime.fromisoformat(e['timestamp'])
            dates.append(dt)
        except Exception:
            dates.append(None)

    valid = [(d, e) for d, e in zip(dates, experiments) if d is not None]
    if not valid:
        return

    dates_valid, exps_valid = zip(*valid)
    aps = np.array([e['ap'] for e in exps_valid])
    running_max = np.maximum.accumulate(aps)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 7), sharex=True,
                                     gridspec_kw={'height_ratios': [2, 1]})

    # (a) AP trajectory with running max
    ax1.scatter(dates_valid, aps, s=3, alpha=0.2, color='#90CAF9', label='Individual experiments')
    ax1.plot(dates_valid, running_max, 'b-', linewidth=2, label='$\\mathrm{AP}^*(t)$')

    # Bug-fix annotations
    bug_fixes = [
        ('2026-03-04', 'Data leakage fix', 0.85),
        ('2026-03-05', 'Focal loss fix', 0.89),
        ('2026-03-06', 'Attn pool +\neval padding fix', 0.90),
    ]
    for date_str, label, y_pos in bug_fixes:
        dt = datetime.fromisoformat(date_str)
        ax1.axvline(x=dt, color='red', linestyle='--', alpha=0.5, linewidth=0.8)
        ax1.annotate(label, xy=(dt, y_pos), fontsize=7,
                     rotation=0, ha='left', va='bottom',
                     bbox=dict(boxstyle='round,pad=0.2', facecolor='lightyellow', alpha=0.8))

    # VJepa2 discovery annotation
    vjepa_date = datetime.fromisoformat('2026-02-24')
    ax1.axvline(x=vjepa_date, color='green', linestyle='--', alpha=0.5, linewidth=0.8)
    ax1.annotate('VJepa2 discovered', xy=(vjepa_date, 0.75), fontsize=7,
                 color='green', ha='left',
                 bbox=dict(boxstyle='round,pad=0.2', facecolor='honeydew', alpha=0.8))

    ax1.set_ylabel('Test AP (Average Precision)', fontsize=10)
    ax1.set_title('(a) AP trajectory with annotated events', fontsize=10)
    ax1.legend(fontsize=8, loc='lower right')
    ax1.grid(True, alpha=0.3)

    # (b) Backbone distribution shift
    # Bin by day
    day_backbone_counts = defaultdict(lambda: defaultdict(int))
    for dt, exp in zip(dates_valid, exps_valid):
        day = dt.date()
        day_backbone_counts[day][exp['backbone']] += 1

    days = sorted(day_backbone_counts.keys())
    backbone_names = ['VJepa2', 'DINOv3', 'DINOv2', 'SigLIP2', 'Other', 'Unknown']
    bb_colors = {
        'VJepa2': '#2196F3',
        'DINOv3': '#FF9800',
        'DINOv2': '#4CAF50',
        'SigLIP2': '#9C27B0',
        'Other': '#9E9E9E',
        'Unknown': '#BDBDBD',
    }

    # Convert to datetime for plotting
    day_dts = [datetime.combine(d, datetime.min.time()) for d in days]

    bottom = np.zeros(len(days))
    for bb in backbone_names:
        counts = np.array([day_backbone_counts[d].get(bb, 0) for d in days], dtype=float)
        totals = np.array([sum(day_backbone_counts[d].values()) for d in days], dtype=float)
        fracs = counts / np.maximum(totals, 1)
        ax2.fill_between(day_dts, bottom, bottom + fracs,
                         alpha=0.7, color=bb_colors.get(bb, '#9E9E9E'), label=bb)
        bottom += fracs

    ax2.set_xlabel('Date', fontsize=10)
    ax2.set_ylabel('Fraction', fontsize=10)
    ax2.set_title('(b) Backbone distribution shift', fontsize=10)
    ax2.legend(fontsize=7, loc='center left', bbox_to_anchor=(1, 0.5))
    ax2.set_ylim(0, 1)
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    fig_path = os.path.join(FIGURES_DIR, 'trajectory.pdf')
    plt.savefig(fig_path, bbox_inches='tight')
    print(f"Saved: {fig_path}", file=sys.stderr)
    plt.close()


def main():
    print("Generating figures...", file=sys.stderr)

    # Figure 1: Schematic
    figure1_schematic()

    # Figure 4: Heatmap
    figure4_heatmap()

    # Figure 5: Trajectory
    figure5_trajectory()

    # Figures 2 and 3 are generated by compute_convergence.py and
    # compute_agent_dynamics.py respectively. We check if they exist.
    for fig_name in ['convergence.pdf', 'agent_dynamics.pdf']:
        fig_path = os.path.join(FIGURES_DIR, fig_name)
        if os.path.exists(fig_path):
            print(f"Found: {fig_path}", file=sys.stderr)
        else:
            print(f"Missing: {fig_path} (run the corresponding compute script first)",
                  file=sys.stderr)

    print("\nAll figures generated.", file=sys.stderr)


if __name__ == '__main__':
    main()
